#! /bin/sh

mount -a

#echo 0 > /proc/sys/kernel/printk

mkdir /var/log
mkdir /var/run

mount -t tmpfs mdev /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

mount -t sysfs sysfs /sys
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

/bin/hostname -F /etc/hostname

#RAID
if command -v mdadm > /dev/null; then
    mdadm -As &> /var/log/mdadm.log
fi
#RAID

#Network
ip link set dev lo up

if [ -f /usr/share/udhcpc/default.script ]; then
    for file in `ls /sys/class/net/ | grep ^eth`
    do
        ip link set dev $file up
        udhcpc -b -i $file -p /var/run/udhcpc-$file.pid -R
    done
fi
#Network

if [ -e /dev/sr0 ]; then
    cd /dev
    ln -s /dev/sr0 /dev/cdrom
    dd if=/dev/cdrom count=1 bs=1 2> /dev/null
    if [ $? -eq 0 ];then
        mkdir -p /mnt/cdrom
        mount /dev/cdrom /mnt/cdrom -t udf,iso9660
    fi
fi
